/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface InviteCodes {
  active: Generated<boolean>
  code: string
  created_at: Generated<Date>
  expires_at: Date | null
  label: string | null
  max_uses: number | null
}

export interface InviteRedemptions {
  access_expires: Date | null
  code: string
  redeemed_at: Generated<Date>
  user_did: string
}

export interface DB {
  invite_codes: InviteCodes
  invite_redemptions: InviteRedemptions
}
